name: Pipeline de Deploy do Portfolio

on:
  push:
    branches: [develop, main]
    tags: ["v*"]

permissions:
  contents: read

jobs:
  dev:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deploy-env.yml
    with:
      ambiente: dev
    secrets: inherit

  staging:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-env.yml
    with:
      ambiente: staging
    secrets: inherit

  prod:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/deploy-env.yml
    with:
      ambiente: prod
    secrets: inherit