on:
  workflow_dispatch:
    inputs:
      ambiente:
        description: 'Qual ambiente destruir?'
        required: true
        type: choice
        options: [dev, staging, prod]
      confirmacao:
        description: 'Digite DESTRUIR'
        required: true
        default: 'NAO'
# no job:
#   if: github.event.inputs.confirmacao == 'DESTRUIR'
#   steps:
#     - terraform init -backend-config="key=portfoliozzz/${{ github.event.inputs.ambiente }}/terraform.tfstate"
#     - terraform plan -destroy -var-file=${{ github.event.inputs.ambiente }}.tfvars
#     - terraform apply -auto-approve destroy.tfplan