name: Terraform CI/CD Portfolio

on:
  workflow_dispatch: # Permite trigger manual do workflow
    inputs:
      apply:
        description: 'Executar o terraform apply?'
        required: true
        default: 'false'
        type: choice #Poderia ser do tipo boolean, mas escolhi choice para deixar mais amigável
        options:
          - true
          - false

      destroy:
        description: 'Destruir ambiente?'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false

      plan_destroy:
        description: 'Planejar o destroy do ambiente?'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false          
permissions:
  id-token: write
  contents: read

jobs:
  job1:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@7

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::614879421397:role/GithubActionsRole
          aws-region: us-east-1

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.1

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        continue-on-error: true
      
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        if: github.event.inputs.apply == 'true' #Se o input apply for true, executa o terraform apply

      - name: Plan Destroy
        run: terraform plan -destroy -out=tfplandestroy
        if: github.event.inputs.plan_destroy == 'true'

      - name: Terraform Destroy
        run: terraform apply -destroy -auto-approve tfplandestroy
        if: github.event.inputs.destroy == 'true'